src/layers/common/pooling.rs

Once I have my nvidia card back this is what needs to be done

feat/pooling: enable average pooling

---

src/layers/common/pooling.rs

Closes #15.
Closes https://github.com/spearow/juice-examples/issues/2.

fix/layers: regression in pooling layer signature change

---

capnp/juice.capnp
src/layer.rs
src/layers/common/dropout.rs
src/layers/common/mod.rs
src/layers/mod.rs
src/util.rs
src/weight.rs
tests/layer_specs.rs

Implement dropout layer

---

coaster-blas/src/frameworks/cuda/helper.rs
coaster-blas/src/frameworks/native.rs
coaster-nn/src/frameworks/cuda/mod.rs
coaster-nn/src/frameworks/native/helper.rs
coaster-nn/src/frameworks/native/mod.rs
coaster/src/backend.rs
coaster/src/frameworks/cuda/api/driver/device.rs
coaster/src/frameworks/cuda/api/driver/memory.rs
coaster/src/frameworks/cuda/api/driver/utils.rs
coaster/src/frameworks/cuda/context.rs
coaster/src/frameworks/cuda/mod.rs
coaster/src/frameworks/opencl/api/context.rs
coaster/src/frameworks/opencl/api/device.rs
coaster/src/frameworks/opencl/api/memory.rs
coaster/src/frameworks/opencl/api/platform.rs
coaster/src/tensor.rs
greenglas/src/transformer.rs
juice/src/layer.rs
juice/src/util.rs

Replace `try!` to `?`

---

Cargo.lock
Cargo.toml
juice-examples/Cargo.toml
juice-examples/src/main.rs

Fix juice-examples

---

Cargo.lock
Cargo.toml
coaster-blas/Cargo.toml
coaster-blas/benches/rblas_overhead.rs
coaster-blas/tests/blas_specs.rs
coaster-nn/Cargo.toml
coaster-nn/src/tests/convolutional.rs
coaster/Cargo.toml
coaster/src/frameworks/cuda/device.rs
coaster/src/frameworks/cuda/module.rs
greenglas/Cargo.toml
juice-examples/Cargo.toml
juice/Cargo.toml
juice/benches/network_benches.rs
juice/src/layer.rs
juice/tests/layer_specs.rs

tests fixes:
* some of failing to build ones
* some failing tests

fix/tests: fix tests

---

coaster-blas/src/frameworks/native.rs
juice/src/layers/common/linear.rs

Implemented a linear bias calculation for the `Linear<f32>` Layer for the Native Backend.

Implemented bias for Linear Layer

---

juice/src/layer.rs
juice/src/layers/common/linear.rs
juice/src/layers/container/sequential.rs
juice/src/solver/mod.rs

Added tests to the Linear layer, corrected compilation issues, and fixed an erroneous transpose in the linear layer.

Fixed compilation issues with current branch and added tests for the Linear layer

---

juice/src/layer.rs
juice/src/layers/common/linear.rs
juice/src/layers/container/sequential.rs
juice/src/solver/mod.rs
juice/src/util.rs

Added the Copy<F> and Copy<f32> to the LayerOps<F> and LayerOps<f32>
trait definitions, respectively.
Addressed comments in #61.

fix/linear: Moved Copy<f32> trait to the LayerOps<f32> definition

---

coaster-nn/src/plugin.rs
juice-examples/Cargo.toml
juice-examples/src/main.rs
juice/src/layers/common/mod.rs
juice/src/layers/common/rnn.rs
juice/src/layers/mod.rs

fix test case rnn_forward_pass - artifact from merge

refactor/rnn: move rnn user inputs to plugin

---

juice/src/layers/common/convolution.rs

Unfortunately there's no unit test for conv layers, so we managed to miss this breaking change when biases were added. Shouldn't affect RNN and Linear had a patch already, but coverage might need to be higher on the roadmap.

fix/conv: add bias into convs to resolve uninitialised tensor issue

---

coaster-blas/Cargo.toml
coaster-nn/Cargo.toml
coaster/Cargo.toml
juice/Cargo.toml
rcublas/cublas/Cargo.toml
rcudnn/cudnn/Cargo.toml
rust-blas/Cargo.toml

Praise contributiors

---

juice/FEATURE-FLAGS.md

docs features flags

---

.github/ISSUE_TEMPLATE/---report-a-bug.md
.github/ISSUE_TEMPLATE/---request-a-new-feature.md
.github/ISSUE_TEMPLATE/--ask-a-question.md
.github/ISSUE_TEMPLATE/config.yml
.github/auto_pr_team.yml
.github/no-response.yml
.github/pull_request_template.md
README.md

An attempt to guide and educate issue filers and cover the most common dependency related issues in the workspace README.md

Introduce issue templates and improve landing README.md

---

.github/FUNDING.yml

* 🪣 Misc
Add `open_collective` directive to `FUNDING.yml`

feat/github: add open_collective

---

Cargo.lock
coaster-blas/Cargo.toml
coaster-nn/Cargo.toml
coaster-nn/src/frameworks/native/helper.rs
coaster-nn/src/lib.rs
coaster/Cargo.toml
coaster/examples/readme.rs
coaster/src/frameworks/cuda/mod.rs
coaster/src/frameworks/native/mod.rs
coaster/src/frameworks/opencl/mod.rs
coaster/tests/shared_memory_specs.rs
greenglas/Cargo.toml
juice-examples/juice-utils/Cargo.toml
juice-examples/juice-utils/src/lib.rs
juice-examples/mackey-glass-rnn-regression/Cargo.toml
juice-examples/mackey-glass-rnn-regression/src/main.rs
juice-examples/mnist-image-multiclass-classification/src/main.rs
juice/tests/layer_specs.rs
rcudnn/cudnn/Cargo.toml
rcudnn/cudnn/src/api/rnn.rs
rcudnn/cudnn/src/api/utils.rs
rcudnn/cudnn/src/rnn_descriptor.rs

Cleanup all crates, fix warnings, move to edition 2018, avoid unneeded dependencies.
* 🩹 Bug Fix
* 🦣 Legacy
* 🪣 Misc
Closes #114 #115

fix/warning: reduce warnings

---

Cargo.lock
coaster-nn/Cargo.toml
coaster-nn/src/frameworks/cuda/helper.rs
coaster-nn/src/frameworks/cuda/mod.rs
coaster-nn/src/frameworks/native/helper.rs
coaster-nn/src/frameworks/native/mod.rs
coaster-nn/src/lib.rs
coaster-nn/src/tests/mod.rs
coaster/benches/shared_tensor.rs
coaster/src/error.rs
coaster/src/framework.rs
coaster/src/frameworks/cuda/api/driver/device.rs
coaster/src/frameworks/opencl/api/memory.rs
coaster/src/frameworks/opencl/api/platform.rs
coaster/src/plugin.rs
coaster/src/tensor.rs
juice/src/layers/common/rnn.rs
rcublas/cublas/src/api/util.rs

* 🩹 Bug Fix
* 🦚 Feature
* 🪣 Misc
Closes #136

improved error handling

---

README.md

* 📙 Documentation
Closes #152  .
Add a note on Archlinux openblas package to README.md

Add a note on Archlinux openblas package to README.md

---

coaster-blas/README.md
coaster-nn/README.md
coaster-nn/src/lib.rs
coaster/src/backend.rs
coaster/src/operation.rs

Small typo fixes in comments here and there. No-op for code.
* 📙 Documentation

Various minor comment spelling fixes.

---

juice/src/lib.rs
juice/src/net/activation/mod.rs
juice/src/net/activation/relu.rs
juice/src/net/config.rs
juice/src/net/context.rs
juice/src/net/descriptor.rs
juice/src/net/layer.rs
juice/src/net/mod.rs
juice/src/net/network.rs

* 🧭 Architecture
Implements core pieces of the new network infrastructure: Layer, Descriptor, Context and Network. 
Includes an implementation of ReLU as an example.
No unit tests so far. After API is agreed upon, I will implement them.

New network architecture pieces: Layer, Descriptor, Context, Network

---

coaster-blas/src/frameworks/cuda/helper.rs

* 🩹 Bug Fix
Fixes the merge error introduced in 6952a490.

Fix merge mistake in commit 6952a490

---

remote-test/README.md
remote-test/test.yml

doc: clarify remote test
